---
title: "Proje Rapor :Mertcan Çalışkan 210401059"
output:
  html_document:
    df_print: paged
---

# Q1 : Problem tanımı

ÇALIŞKAN e-commerse şirketi olarak müşteri iade oranları ve churn olasılıkları yüksek olduğundan, şirketin karlılığını olumsuz etkileyen bir problemle karşı karşıyayız. Bu durumu çözmek için müşteri segmentasyonu ve özel tekliflerle müşteri sadakatini artırıcı stratejiler geliştirmemiz gerekmektedir.


# Q2 : Proje Amacı
Bu projenin temel amacı, müşteri iade oranlarını ve churn olasılıklarını azaltarak şirketin karlılığını artırmaktır. İlk olarak, müşteri segmentasyonu yapılacak ve bu analiz sonucunda hangi müşteri gruplarının iade eğilimi gösterdiği belirlenecektir. Bu bilgi, şirketin iade politikalarını ve müşteri hizmetlerini optimize etmek için kullanılacaktır.

İkinci olarak, müşteri aktiviteleri üzerinden churn olasılıkları değerlendirilecek ve müşteri kayıplarını minimize etmek adına stratejiler geliştirilecektir. Bu, müşteri memnuniyetini artırmak ve uzun vadeli müşteri sadakatini sağlamak amacıyla özel teklifler ve avantajlar sunmak anlamına gelebilir.

Analiz etapları, R programlama dili kullanılarak veri setinin detaylı bir şekilde incelenmesini ve müşteri davranışlarının anlaşılmasını içerecek. Sonuç olarak, iade eğilimi yüksek olan müşteri segmentleri belirlenecek ve bu segmentlere özel tekliflerle müşteri sadakati artırılacaktır. Aynı zamanda, churn olasılıkları üzerinden müşteri kayıpları minimize edilerek şirketin karlılığı artırılacaktır.